In [ ]:
#1首先提取target_index = ['000300.XSHG','000905.XSHG', '000852.XSHG','932000.INDX','000922.XSHG']的成分股
#index_weights(order_book_id, date=None) 提取全A
#rqdatac.index_weights_ex(order_book_id, date=None, start_date=None, end_date=None, market='cn') 提取其余

#2提取并集的股票行业信息：
#get_instrument_industry(order_book_ids, source='citics_2019', level=1, date=None, market='cn')

#3提取科创板、创业板的成分股ban_index = ["399006.XSHE","000680.XSHG"]
#index_components(order_book_id, date=None, start_date, end_date, market='cn',return_create_tm=False)

In [22]:
import rqdatac
rqdatac.init(
    username = "license",
    password = "ZZ-u7ZWosqrntc3VY3TJzJLPsb-A0o4zehYoiNpDvIBXiwvRIOUmFe7medtMhwu4qiaNxqFSc6ONdGcGeVYgUVd-w5QKScPkmzBEmYVEt94lz9sQZoHwdtQXWWRGGrJqtr7ehiQACydlPS7RcPBfJrpyeTJFsGF1E1guZbpLnvU=XouX9YSi7Pcyo0rSLCMydvHs3nrVq6Rwjda-jI9H_gfGlp53ot0ZnIA6g-ZtvwPDAb62K38pHIqYYyTAyER7FBtZ5HumXzOrWW42LHpUn5-vbnLMxiwbimJ9ns41CaMbjpFEgNcfO52l5wiqDqFCkZNy_OKSDjepfa9GxHsLZZE="
)
from rqdatac import *
import pandas as pd
import numpy as np
import pickle
import os

d:\Ana\envs\rqsdk\lib\site-packages\rqdatac\client.py:224: UserWarning: rqdatac is already inited. Settings will be changed.
  warnings.warn("rqdatac is already inited. Settings will be changed.", stacklevel=0)
d:\Ana\envs\rqsdk\lib\site-packages\rqdatac\client.py:263: UserWarning: Your account will be expired after  32 days. Please call us at 0755-22676337 to upgrade or purchase or renew your contract.
  warnings.warn("Your account will be expired after  {} days. "

In [ ]:
srcdir = "E:/SJTU/实习/国泰海通/barra因子/data_base/index/component"
df_kj = pd.read_pickle(f"{srcdir}/866011.RI_20_26M_dict.pkl")

#补齐双板的权重数据
dates = df_kj.index.get_level_values(0).unique()
for ban in ['399006.XSHE',"000680.XSHG"]:
    res_dict = {}
    for dt in dates:
        temp = index_weights(ban, dt)
        res_dict[dt] = temp
        # 将字典保存为pkl文件
        pd.to_pickle(res_dict, f"{srcdir}/{ban}_20_26M_weights_dict.pkl")

In [47]:
df_kj

{Timestamp('2020-01-23 00:00:00'): order_book_id
 000001.XSHE    0.006257
 000002.XSHE    0.007986
 000004.XSHE    0.000057
 000005.XSHE    0.000104
 000006.XSHE    0.000187
                  ...
 688368.XSHG    0.000070
 688369.XSHG    0.000048
 688388.XSHG    0.000140
 688389.XSHG    0.000028
 688399.XSHG    0.000056
 Name: weight, Length: 3764, dtype: float64,
 Timestamp('2020-02-28 00:00:00'): order_book_id
 000001.XSHE    0.004988
 000002.XSHE    0.008073
 000004.XSHE    0.000101
 000005.XSHE    0.000097
 000006.XSHE    0.000168
                  ...
 688369.XSHG    0.000057
 688388.XSHG    0.000142
 688389.XSHG    0.000033
 688398.XSHG    0.000045
 688399.XSHG    0.000054
 Name: weight, Length: 3788, dtype: float64,
 Timestamp('2020-03-31 00:00:00'): order_book_id
 000001.XSHE    0.004670
 000002.XSHE    0.007423
 000004.XSHE    0.000080
 000005.XSHE    0.000101
 000006.XSHE    0.000173
                  ...
 688388.XSHG    0.000115
 688389.XSHG    0.000029
 688396.XSHG    0.000343
 688398.XSHG    0.000037
 688399.XSHG    0.000045
 Name: weight, Length: 3804, dtype: float64,
 Timestamp('2020-04-30 00:00:00'): order_book_id
 000001.XSHE    0.004793
 000002.XSHE    0.007314
 000004.XSHE    0.000069
 000005.XSHE    0.000093
 000006.XSHE    0.000181
                  ...
 688388.XSHG    0.000142
 688389.XSHG    0.000031
 688396.XSHG    0.000378
 688398.XSHG    0.000038
 688399.XSHG    0.000068
 Name: weight, Length: 3821, dtype: float64,
 Timestamp('2020-05-29 00:00:00'): order_book_id
 000001.XSHE    0.004428
 000002.XSHE    0.006943
 000004.XSHE    0.000071
 000005.XSHE    0.000088
 000006.XSHE    0.000173
                  ...
 688399.XSHG    0.000101
 688466.XSHG    0.000038
 688566.XSHG    0.000069
 688588.XSHG    0.000062
 688598.XSHG    0.000067
 Name: weight, Length: 3843, dtype: float64,
 Timestamp('2020-06-30 00:00:00'): order_book_id
 000001.XSHE    0.004001
 000002.XSHE    0.006480
 000004.XSHE    0.000067
 000005.XSHE    0.000082
 000006.XSHE    0.000225
                  ...
 688516.XSHG    0.000042
 688566.XSHG    0.000067
 688588.XSHG    0.000062
 688598.XSHG    0.000065
 688599.XSHG    0.000184
 Name: weight, Length: 3864, dtype: float64,
 Timestamp('2020-07-31 00:00:00'): order_book_id
 000001.XSHE    0.003630
 000002.XSHE    0.005792
 000004.XSHE    0.000056
 000005.XSHE    0.000079
 000006.XSHE    0.000238
                  ...
 688588.XSHG    0.000048
 688598.XSHG    0.000057
 688599.XSHG    0.000161
 688600.XSHG    0.000028
 688981.XSHG    0.002851
 Name: weight, Length: 3901, dtype: float64,
 Timestamp('2020-08-31 00:00:00'): order_book_id
 000001.XSHE    0.003997
 000002.XSHE    0.005732
 000004.XSHE    0.000049
 000005.XSHE    0.000079
 000006.XSHE    0.000179
                  ...
 688589.XSHG    0.000042
 688598.XSHG    0.000061
 688599.XSHG    0.000156
 688600.XSHG    0.000025
 688981.XSHG    0.002253
 Name: weight, Length: 3943, dtype: float64,
 Timestamp('2020-09-30 00:00:00'): order_book_id
 000001.XSHE    0.004226
 000002.XSHE    0.006190
 000004.XSHE    0.000046
 000005.XSHE    0.000068
 000006.XSHE    0.000189
                  ...
 688596.XSHG    0.000043
 688598.XSHG    0.000063
 688599.XSHG    0.000165
 688600.XSHG    0.000023
 688981.XSHG    0.001763
 Name: weight, Length: 4009, dtype: float64,
 Timestamp('2020-10-30 00:00:00'): order_book_id
 000001.XSHE    0.004859
 000002.XSHE    0.005981
 000004.XSHE    0.000052
 000005.XSHE    0.000066
 000006.XSHE    0.000165
                  ...
 688596.XSHG    0.000041
 688598.XSHG    0.000069
 688599.XSHG    0.000157
 688600.XSHG    0.000020
 688981.XSHG    0.002172
 Name: weight, Length: 4051, dtype: float64,
 Timestamp('2020-11-30 00:00:00'): order_book_id
 000001.XSHE    0.005145
 000002.XSHE    0.006346
 000004.XSHE    0.000052
 000005.XSHE    0.000064
 000006.XSHE    0.000158
                  ...
 688599.XSHG    0.000204
 688600.XSHG    0.000020
 688788.XSHG    0.000122
 688981.XSHG    0.001969
 689009.XSHG    0.000013
 Name: weight, Length: 4079, dtype: float64,
 Timestamp('2020-12-31 00:00:00'): order_book_id
 000001.XSHE    0.004808
 000002.XSHE    0.005659
 000004.XSHE    0.000037
 000005.XSHE    0.000060
 000006.XSHE    0.000147
                  ...
 688699.XSHG    0.000028
 688777.XSHG    0.000119
 688788.XSHG    0.000068
 688981.XSHG    0.001830
 689009.XSHG    0.000015
 Name: weight, Length: 4115, dtype: float64,
 Timestamp('2021-01-29 00:00:00'): order_book_id
 000001.XSHE    0.005686
 000002.XSHE    0.005427
 000004.XSHE    0.000047
 000005.XSHE    0.000050
 000006.XSHE    0.000126
                  ...
 688777.XSHG    0.000098
 688788.XSHG    0.000060
 688819.XSHG    0.000162
 688981.XSHG    0.001857
 689009.XSHG    0.000017
 Name: weight, Length: 4152, dtype: float64,
 Timestamp('2021-02-26 00:00:00'): order_book_id
 000001.XSHE    0.005226
 000002.XSHE    0.006416
 000004.XSHE    0.000044
 000005.XSHE    0.000050
 000006.XSHE    0.000133
                  ...
 688777.XSHG    0.000098
 688788.XSHG    0.000062
 688819.XSHG    0.000132
 688981.XSHG    0.001810
 689009.XSHG    0.000012
 Name: weight, Length: 4183, dtype: float64,
 Timestamp('2021-03-31 00:00:00'): order_book_id
 000001.XSHE    0.005530
 000002.XSHE    0.005981
 000004.XSHE    0.000041
 000005.XSHE    0.000058
 000006.XSHE    0.000141
                  ...
 688777.XSHG    0.000092
 688788.XSHG    0.000051
 688819.XSHG    0.000145
 688981.XSHG    0.001833
 689009.XSHG    0.000012
 Name: weight, Length: 4214, dtype: float64,
 Timestamp('2021-04-30 00:00:00'): order_book_id
 000001.XSHE    0.005681
 000002.XSHE    0.005452
 000004.XSHE    0.000037
 000005.XSHE    0.000054
 000006.XSHE    0.000137
                  ...
 688777.XSHG    0.000101
 688788.XSHG    0.000052
 688819.XSHG    0.000127
 688981.XSHG    0.001791
 689009.XSHG    0.000013
 Name: weight, Length: 4263, dtype: float64,
 Timestamp('2021-05-31 00:00:00'): order_book_id
 000001.XSHE    0.005580
 000002.XSHE    0.004885
 000004.XSHE    0.000035
 000005.XSHE    0.000040
 000006.XSHE    0.000126
                  ...
 688777.XSHG    0.000109
 688788.XSHG    0.000070
 688819.XSHG    0.000122
 688981.XSHG    0.001742
 689009.XSHG    0.000013
 Name: weight, Length: 4307, dtype: float64,
 Timestamp('2021-06-30 00:00:00'): order_book_id
 000001.XSHE    0.005116
 000002.XSHE    0.004273
 000004.XSHE    0.000040
 000005.XSHE    0.000042
 000006.XSHE    0.000118
                  ...
 688777.XSHG    0.000107
 688788.XSHG    0.000070
 688819.XSHG    0.000125
 688981.XSHG    0.001877
 689009.XSHG    0.000014
 Name: weight, Length: 4351, dtype: float64,
 Timestamp('2021-07-30 00:00:00'): order_book_id
 000001.XSHE    0.004100
 000002.XSHE    0.003799
 000004.XSHE    0.000049
 000005.XSHE    0.000048
 000006.XSHE    0.000107
                  ...
 688793.XSHG    0.000043
 688799.XSHG    0.000024
 688819.XSHG    0.000176
 688981.XSHG    0.003438
 689009.XSHG    0.000012
 Name: weight, Length: 4394, dtype: float64,
 Timestamp('2021-08-31 00:00:00'): order_book_id
 000001.XSHE    0.003961
 000002.XSHE    0.003513
 000004.XSHE    0.000042
 000005.XSHE    0.000053
 000006.XSHE    0.000105
                  ...
 688799.XSHG    0.000020
 688800.XSHG    0.000056
 688819.XSHG    0.000141
 688981.XSHG    0.002841
 689009.XSHG    0.000012
 Name: weight, Length: 4444, dtype: float64,
 Timestamp('2021-09-30 00:00:00'): order_book_id
 000001.XSHE    0.004000
 000002.XSHE    0.003791
 000004.XSHE    0.000041
 000005.XSHE    0.000047
 000006.XSHE    0.000104
                  ...
 688799.XSHG    0.000020
 688800.XSHG    0.000041
 688819.XSHG    0.000127
 688981.XSHG    0.002823
 689009.XSHG    0.000013
 Name: weight, Length: 4477, dtype: float64,
 Timestamp('2021-10-29 00:00:00'): order_book_id
 000001.XSHE    0.004312
 000002.XSHE    0.003211
 000004.XSHE    0.000036
 000005.XSHE    0.000048
 000006.XSHE    0.000096
                  ...
 688799.XSHG    0.000019
 688800.XSHG    0.000051
 688819.XSHG    0.000117
 688981.XSHG    0.002790
 689009.XSHG    0.000028
 Name: weight, Length: 4502, dtype: float64,
 Timestamp('2021-11-30 00:00:00'): order_book_id
 000001.XSHE    0.003706
 000002.XSHE    0.003094
 000004.XSHE    0.000039
 000005.XSHE    0.000046
 000006.XSHE    0.000091
                  ...
 688799.XSHG    0.000020
 688800.XSHG    0.000077
 688819.XSHG    0.000134
 688981.XSHG    0.002643
 689009.XSHG    0.000035
 Name: weight, Length: 4546, dtype: float64,
 Timestamp('2021-12-31 00:00:00'): order_book_id
 000001.XSHE    0.003424
 000002.XSHE    0.003274
 000004.XSHE    0.000039
 000005.XSHE    0.000048
 000006.XSHE    0.000097
                  ...
 688799.XSHG    0.000020
 688800.XSHG    0.000078
 688819.XSHG    0.000116
 688981.XSHG    0.002524
 689009.XSHG    0.000044
 Name: weight, Length: 4584, dtype: float64,
 Timestamp('2022-01-28 00:00:00'): order_book_id
 000001.XSHE    0.003614
 000002.XSHE    0.003701
 000004.XSHE    0.000047
 000005.XSHE    0.000049
 000006.XSHE    0.000102
                  ...
 688799.XSHG    0.000020
 688800.XSHG    0.000071
 688819.XSHG    0.000133
 688981.XSHG    0.002576
 689009.XSHG    0.000042
 Name: weight, Length: 4617, dtype: float64,
 Timestamp('2022-02-28 00:00:00'): order_book_id
 000001.XSHE    0.003480
 000002.XSHE    0.003383
 000004.XSHE    0.000047
 000005.XSHE    0.000049
 000006.XSHE    0.000100
                  ...
 688799.XSHG    0.000020
 688800.XSHG    0.000067
 688819.XSHG    0.000126
 688981.XSHG    0.002570
 689009.XSHG    0.000038
 Name: weight, Length: 4637, dtype: float64,
 Timestamp('2022-03-31 00:00:00'): order_book_id
 000001.XSHE    0.003663
 000002.XSHE    0.003618
 000004.XSHE    0.000048
 000005.XSHE    0.000054
 000006.XSHE    0.000128
                  ...
 688799.XSHG    0.000023
 688800.XSHG    0.000077
 688819.XSHG    0.000121
 688981.XSHG    0.002370
 689009.XSHG    0.000040
 Name: weight, Length: 4666, dtype: float64,
 Timestamp('2022-04-29 00:00:00'): order_book_id
 000001.XSHE    0.004036
 000002.XSHE    0.004051
 000004.XSHE    0.000033
 000005.XSHE    0.000049
 000006.XSHE    0.000120
                  ...
 688799.XSHG    0.000020
 688800.XSHG    0.000072
 688819.XSHG    0.000105
 688981.XSHG    0.002260
 689009.XSHG    0.000038
 Name: weight, Length: 4692, dtype: float64,
 Timestamp('2022-05-31 00:00:00'): order_book_id
 000001.XSHE    0.003500
 000002.XSHE    0.003493
 000004.XSHE    0.000024
 000005.XSHE    0.000047
 000006.XSHE    0.000114
                  ...
 688799.XSHG    0.000018
 688800.XSHG    0.000072
 688819.XSHG    0.000123
 688981.XSHG    0.002289
 689009.XSHG    0.000045
 Name: weight, Length: 4716, dtype: float64,
 Timestamp('2022-06-30 00:00:00'): order_book_id
 000001.XSHE    0.003368
 000002.XSHE    0.003657
 000004.XSHE    0.000020
 000005.XSHE    0.000041
 000006.XSHE    0.000110
                  ...
 688799.XSHG    0.000018
 688800.XSHG    0.000080
 688819.XSHG    0.000122
 688981.XSHG    0.002193
 689009.XSHG    0.000040
 Name: weight, Length: 4708, dtype: float64,
 Timestamp('2022-07-29 00:00:00'): order_book_id
 000001.XSHE    0.002916
 000002.XSHE    0.003141
 000004.XSHE    0.000021
 000005.XSHE    0.000042
 000006.XSHE    0.000101
                  ...
 688799.XSHG    0.000035
 688800.XSHG    0.000213
 688819.XSHG    0.000152
 688981.XSHG    0.002067
 689009.XSHG    0.000046
 Name: weight, Length: 4730, dtype: float64,
 Timestamp('2022-08-31 00:00:00'): order_book_id
 000001.XSHE    0.003004
 000002.XSHE    0.003108
 000004.XSHE    0.000022
 000005.XSHE    0.000043
 000006.XSHE    0.000103
                  ...
 688799.XSHG    0.000037
 688800.XSHG    0.000213
 688819.XSHG    0.000146
 688981.XSHG    0.002124
 689009.XSHG    0.000043
 Name: weight, Length: 4771, dtype: float64,
 Timestamp('2022-09-30 00:00:00'): order_book_id
 000001.XSHE    0.003004
 000002.XSHE    0.003589
 000004.XSHE    0.000021
 000005.XSHE    0.000043
 000006.XSHE    0.000109
                  ...
 688799.XSHG    0.000039
 688800.XSHG    0.000247
 688819.XSHG    0.000133
 688981.XSHG    0.002171
 689009.XSHG    0.000040
 Name: weight, Length: 4809, dtype: float64,
 Timestamp('2022-10-31 00:00:00'): order_book_id
 000001.XSHE    0.002672
 000002.XSHE    0.002772
 000004.XSHE    0.000022
 000005.XSHE    0.000043
 000006.XSHE    0.000099
                  ...
 688799.XSHG    0.000047
 688800.XSHG    0.000209
 688819.XSHG    0.000169
 688981.XSHG    0.002441
 689009.XSHG    0.000035
 Name: weight, Length: 4839, dtype: float64,
 Timestamp('2022-11-30 00:00:00'): order_book_id
 000001.XSHE    0.003111
 000002.XSHE    0.003533
 000004.XSHE    0.000024
 000005.XSHE    0.000045
 000006.XSHE    0.000145
                  ...
 688799.XSHG    0.000042
 688800.XSHG    0.000202
 688819.XSHG    0.000145
 688981.XSHG    0.002209
 689009.XSHG    0.000034
 Name: weight, Length: 4869, dtype: float64,
 Timestamp('2022-12-30 00:00:00'): order_book_id
 000001.XSHE    0.003195
 000002.XSHE    0.003506
 000004.XSHE    0.000023
 000005.XSHE    0.000045
 000006.XSHE    0.000159
                  ...
 688799.XSHG    0.000040
 688800.XSHG    0.000194
 688819.XSHG    0.000142
 688981.XSHG    0.002263
 689009.XSHG    0.000032
 Name: weight, Length: 4892, dtype: float64,
 Timestamp('2023-01-31 00:00:00'): order_book_id
 000001.XSHE    0.003362
 000002.XSHE    0.003255
 000004.XSHE    0.000024
 000005.XSHE    0.000041
 000006.XSHE    0.000132
                  ...
 688799.XSHG    0.000040
 688800.XSHG    0.000177
 688819.XSHG    0.000142
 688981.XSHG    0.002127
 689009.XSHG    0.000032
 Name: weight, Length: 4907, dtype: float64,
 Timestamp('2023-02-28 00:00:00'): order_book_id
 000001.XSHE    0.003079
 000002.XSHE    0.003038
 000004.XSHE    0.000022
 000005.XSHE    0.000040
 000006.XSHE    0.000133
                  ...
 688799.XSHG    0.000042
 688800.XSHG    0.000166
 688819.XSHG    0.000133
 688981.XSHG    0.002127
 689009.XSHG    0.000031
 Name: weight, Length: 4918, dtype: float64,
 Timestamp('2023-03-31 00:00:00'): order_book_id
 000001.XSHE    0.002806
 000002.XSHE    0.002707
 000004.XSHE    0.000022
 000005.XSHE    0.000040
 000006.XSHE    0.000119
                  ...
 688799.XSHG    0.000043
 688800.XSHG    0.000151
 688819.XSHG    0.000124
 688981.XSHG    0.002542
 689009.XSHG    0.000036
 Name: weight, Length: 4940, dtype: float64,
 Timestamp('2023-04-28 00:00:00'): order_book_id
 000001.XSHE    0.002843
 000002.XSHE    0.002721
 000004.XSHE    0.000024
 000005.XSHE    0.000040
 000006.XSHE    0.000114
                  ...
 688799.XSHG    0.000048
 688800.XSHG    0.000138
 688819.XSHG    0.000121
 688981.XSHG    0.003160
 689009.XSHG    0.000032
 Name: weight, Length: 4964, dtype: float64,
 Timestamp('2023-05-31 00:00:00'): order_book_id
 000001.XSHE    0.002713
 000002.XSHE    0.002642
 000004.XSHE    0.000032
 000005.XSHE    0.000024
 000006.XSHE    0.000113
                  ...
 688799.XSHG    0.000047
 688800.XSHG    0.000138
 688819.XSHG    0.000132
 688981.XSHG    0.002884
 689009.XSHG    0.000033
 Name: weight, Length: 4984, dtype: float64,
 Timestamp('2023-06-30 00:00:00'): order_book_id
 000001.XSHE    0.002586
 000002.XSHE    0.002561
 000004.XSHE    0.000036
 000005.XSHE    0.000029
 000006.XSHE    0.000105
                  ...
 688799.XSHG    0.000046
 688800.XSHG    0.000159
 688819.XSHG    0.000136
 688981.XSHG    0.002637
 689009.XSHG    0.000037
 Name: weight, Length: 5001, dtype: float64,
 Timestamp('2023-07-31 00:00:00'): order_book_id
 000001.XSHE    0.002772
 000002.XSHE    0.002722
 000004.XSHE    0.000042
 000005.XSHE    0.000031
 000006.XSHE    0.000120
                  ...
 688799.XSHG    0.000047
 688800.XSHG    0.000133
 688819.XSHG    0.000134
 688981.XSHG    0.002619
 689009.XSHG    0.000034
 Name: weight, Length: 5016, dtype: float64,
 Timestamp('2023-08-31 00:00:00'): order_book_id
 000001.XSHE    0.002631
 000002.XSHE    0.002558
 000004.XSHE    0.000041
 000005.XSHE    0.000034
 000006.XSHE    0.000129
                  ...
 688799.XSHG    0.000049
 688800.XSHG    0.000115
 688819.XSHG    0.000135
 688981.XSHG    0.002961
 689009.XSHG    0.000036
 Name: weight, Length: 5044, dtype: float64,
 Timestamp('2023-09-28 00:00:00'): order_book_id
 000001.XSHE    0.002670
 000002.XSHE    0.002474
 000004.XSHE    0.000040
 000005.XSHE    0.000035
 000006.XSHE    0.000113
                  ...
 688799.XSHG    0.000049
 688800.XSHG    0.000108
 688819.XSHG    0.000133
 688981.XSHG    0.002841
 689009.XSHG    0.000037
 Name: weight, Length: 5059, dtype: float64,
 Timestamp('2023-10-31 00:00:00'): order_book_id
 000001.XSHE    0.002537
 000002.XSHE    0.002180
 000004.XSHE    0.000044
 000005.XSHE    0.000035
 000006.XSHE    0.000109
                  ...
 688799.XSHG    0.000056
 688800.XSHG    0.000111
 688819.XSHG    0.000125
 688981.XSHG    0.003235
 689009.XSHG    0.000041
 Name: weight, Length: 5069, dtype: float64,
 Timestamp('2023-11-30 00:00:00'): order_book_id
 000001.XSHE    0.002331
 000002.XSHE    0.002185
 000004.XSHE    0.000044
 000005.XSHE    0.000034
 000006.XSHE    0.000116
                  ...
 688799.XSHG    0.000054
 688800.XSHG    0.000122
 688819.XSHG    0.000114
 688981.XSHG    0.003013
 689009.XSHG    0.000041
 Name: weight, Length: 5080, dtype: float64,
 Timestamp('2023-12-29 00:00:00'): order_book_id
 000001.XSHE    0.002301
 000002.XSHE    0.002033
 000004.XSHE    0.000041
 000005.XSHE    0.000027
 000006.XSHE    0.000117
                  ...
 688799.XSHG    0.000060
 688800.XSHG    0.000114
 688819.XSHG    0.000110
 688981.XSHG    0.003027
 689009.XSHG    0.000038
 Name: weight, Length: 5090, dtype: float64,
 Timestamp('2024-01-31 00:00:00'): order_book_id
 000001.XSHE    0.002656
 000002.XSHE    0.002138
 000004.XSHE    0.000036
 000005.XSHE    0.000027
 000006.XSHE    0.000122
                  ...
 688799.XSHG    0.000053
 688800.XSHG    0.000086
 688819.XSHG    0.000111
 688981.XSHG    0.002831
 689009.XSHG    0.000031
 Name: weight, Length: 5101, dtype: float64,
 Timestamp('2024-02-29 00:00:00'): order_book_id
 000001.XSHE    0.002700
 000002.XSHE    0.002031
 000004.XSHE    0.000033
 000005.XSHE    0.000025
 000006.XSHE    0.000108
                  ...
 688799.XSHG    0.000056
 688800.XSHG    0.000085
 688819.XSHG    0.000119
 688981.XSHG    0.002872
 689009.XSHG    0.000036
 Name: weight, Length: 5108, dtype: float64,
 Timestamp('2024-03-29 00:00:00'): order_book_id
 000001.XSHE    0.002642
 000002.XSHE    0.001793
 000004.XSHE    0.000040
 000005.XSHE    0.000021
 000006.XSHE    0.000103
                  ...
 688799.XSHG    0.000064
 688800.XSHG    0.000090
 688819.XSHG    0.000115
 688981.XSHG    0.002554
 689009.XSHG    0.000035
 Name: weight, Length: 5109, dtype: float64,
 Timestamp('2024-04-30 00:00:00'): order_book_id
 000001.XSHE    0.002681
 000002.XSHE    0.001461
 000004.XSHE    0.000027
 000006.XSHE    0.000100
 000007.XSHE    0.000030
                  ...
 688799.XSHG    0.000056
 688800.XSHG    0.000088
 688819.XSHG    0.000115
 688981.XSHG    0.002426
 689009.XSHG    0.000043
 Name: weight, Length: 5114, dtype: float64,
 Timestamp('2024-05-31 00:00:00'): order_book_id
 000001.XSHE    0.002792
 000002.XSHE    0.001645
 000004.XSHE    0.000027
 000006.XSHE    0.000100
 000007.XSHE    0.000035
                  ...
 688799.XSHG    0.000054
 688800.XSHG    0.000086
 688819.XSHG    0.000113
 688981.XSHG    0.002626
 689009.XSHG    0.000044
 Name: weight, Length: 5116, dtype: float64,
 Timestamp('2024-06-28 00:00:00'): order_book_id
 000001.XSHE    0.002703
 000002.XSHE    0.001464
 000004.XSHE    0.000033
 000006.XSHE    0.000108
 000007.XSHE    0.000036
                  ...
 688799.XSHG    0.000056
 688800.XSHG    0.000085
 688819.XSHG    0.000102
 688981.XSHG    0.002860
 689009.XSHG    0.000046
 Name: weight, Length: 5112, dtype: float64,
 Timestamp('2024-07-31 00:00:00'): order_book_id
 000001.XSHE    0.002748
 000002.XSHE    0.001505
 000004.XSHE    0.000033
 000006.XSHE    0.000107
 000007.XSHE    0.000038
                  ...
 688799.XSHG    0.000052

In [57]:
ret_dict = {}
df_kj = pd.read_pickle(f"{srcdir}/866011.RI_20_26M_dict.pkl")
dates = df_kj.keys()
desdir = "E:/SJTU/实习/国泰海通/barra因子/data_base/stk_ret"

for dt in dates:
   stk = df_kj[dt].index.tolist()
   temp = get_price_change_rate(stk, start_date=dt, end_date=dt, expect_df=True, market='cn')
   df_long = temp.stack().to_frame('value')
   df_long.index.names = ['date', 'order_book_id']
   ret_dict[dt] = df_long
   print(dt)
pd.to_pickle(ret_dict,f"{desdir}/全A_ret_dict.pkl")

2020-01-23 00:00:00
2020-02-28 00:00:00
2020-03-31 00:00:00
2020-04-30 00:00:00
2020-05-29 00:00:00
2020-06-30 00:00:00
2020-07-31 00:00:00
2020-08-31 00:00:00
2020-09-30 00:00:00
2020-10-30 00:00:00
2020-11-30 00:00:00
2020-12-31 00:00:00
2021-01-29 00:00:00
2021-02-26 00:00:00
2021-03-31 00:00:00
2021-04-30 00:00:00
2021-05-31 00:00:00
2021-06-30 00:00:00
2021-07-30 00:00:00
2021-08-31 00:00:00
2021-09-30 00:00:00
2021-10-29 00:00:00
2021-11-30 00:00:00
2021-12-31 00:00:00
2022-01-28 00:00:00
2022-02-28 00:00:00
2022-03-31 00:00:00
2022-04-29 00:00:00
2022-05-31 00:00:00
2022-06-30 00:00:00
2022-07-29 00:00:00
2022-08-31 00:00:00
2022-09-30 00:00:00
2022-10-31 00:00:00
2022-11-30 00:00:00
2022-12-30 00:00:00
2023-01-31 00:00:00
2023-02-28 00:00:00
2023-03-31 00:00:00
2023-04-28 00:00:00
2023-05-31 00:00:00
2023-06-30 00:00:00
2023-07-31 00:00:00
2023-08-31 00:00:00
2023-09-28 00:00:00
2023-10-31 00:00:00
2023-11-30 00:00:00
2023-12-29 00:00:00
2024-01-31 00:00:00
2024-02-29 00:00:00
2024-03-29 00:00:00
2024-04-30 00:00:00
2024-05-31 00:00:00
2024-06-28 00:00:00
2024-07-31 00:00:00
2024-08-30 00:00:00
2024-09-30 00:00:00
2024-10-31 00:00:00
2024-11-29 00:00:00
2024-12-31 00:00:00
2025-01-27 00:00:00
2025-02-28 00:00:00
2025-03-31 00:00:00
2025-04-30 00:00:00
2025-05-30 00:00:00
2025-06-30 00:00:00
2025-07-31 00:00:00
2025-08-29 00:00:00
2025-09-30 00:00:00
2025-10-31 00:00:00
2025-11-28 00:00:00
2025-12-31 00:00:00
2026-01-30 00:00:00
2026-02-27 00:00:00
2026-03-31 00:00:00

In [78]:
mcp_dict = {}
desdir = "E:/SJTU/实习/国泰海通/barra因子/data_base/stk_mcp"
for dt in dates:
    stk = df_kj[dt].index.tolist()
    a = get_shares(stk, start_date=dt, end_date=dt, fields='free_circulation', expect_df=True, market='cn').droplevel(1)
    b = get_price(stk, start_date=dt, end_date=dt, frequency='1d', fields="close", adjust_type='pre', skip_suspended=False, expect_df=True, time_slice=None, market='cn').droplevel(1)
    df = a.merge(b[["close"]],on="order_book_id",how="left")
    df["free_mkp"] = df["free_circulation"]*df["close"]
    mcp_dict[dt] = df
    print(dt)
    
pd.to_pickle(mcp_dict, f"{desdir}/全A_freemcp_20_26M_dict.pkl")

2020-01-23 00:00:00
2020-02-28 00:00:00
2020-03-31 00:00:00
2020-04-30 00:00:00
2020-05-29 00:00:00
2020-06-30 00:00:00
2020-07-31 00:00:00
2020-08-31 00:00:00
2020-09-30 00:00:00
2020-10-30 00:00:00
2020-11-30 00:00:00
2020-12-31 00:00:00
2021-01-29 00:00:00
2021-02-26 00:00:00
2021-03-31 00:00:00
2021-04-30 00:00:00
2021-05-31 00:00:00
2021-06-30 00:00:00
2021-07-30 00:00:00
2021-08-31 00:00:00
2021-09-30 00:00:00
2021-10-29 00:00:00
2021-11-30 00:00:00
2021-12-31 00:00:00
2022-01-28 00:00:00
2022-02-28 00:00:00
2022-03-31 00:00:00
2022-04-29 00:00:00
2022-05-31 00:00:00
2022-06-30 00:00:00
2022-07-29 00:00:00
2022-08-31 00:00:00
2022-09-30 00:00:00
2022-10-31 00:00:00
2022-11-30 00:00:00
2022-12-30 00:00:00
2023-01-31 00:00:00
2023-02-28 00:00:00
2023-03-31 00:00:00
2023-04-28 00:00:00
2023-05-31 00:00:00
2023-06-30 00:00:00
2023-07-31 00:00:00
2023-08-31 00:00:00
2023-09-28 00:00:00
2023-10-31 00:00:00
2023-11-30 00:00:00
2023-12-29 00:00:00
2024-01-31 00:00:00
2024-02-29 00:00:00
2024-03-29 00:00:00
2024-04-30 00:00:00
2024-05-31 00:00:00
2024-06-28 00:00:00
2024-07-31 00:00:00
2024-08-30 00:00:00
2024-09-30 00:00:00
2024-10-31 00:00:00
2024-11-29 00:00:00
2024-12-31 00:00:00
2025-01-27 00:00:00
2025-02-28 00:00:00
2025-03-31 00:00:00
2025-04-30 00:00:00
2025-05-30 00:00:00
2025-06-30 00:00:00
2025-07-31 00:00:00
2025-08-29 00:00:00
2025-09-30 00:00:00
2025-10-31 00:00:00
2025-11-28 00:00:00
2025-12-31 00:00:00
2026-01-30 00:00:00
2026-02-27 00:00:00
2026-03-31 00:00:00

In [79]:
df

               free_circulation  close      free_mkp
order_book_id
000001.XSHE        8.160481e+09  11.08  9.041813e+10
000002.XSHE        6.473589e+09   3.99  2.582962e+10
000004.XSHE        9.339358e+07   4.57  4.268087e+08
000006.XSHE        8.505992e+08   8.60  7.315154e+09
000007.XSHE        2.299860e+08  12.95  2.978318e+09
...                         ...    ...           ...
688816.XSHG        1.928424e+07  61.53  1.186559e+09
688818.XSHG        1.320163e+08  60.74  8.018672e+09
688819.XSHG        1.309000e+08  32.31  4.229379e+09
688981.XSHG        1.927092e+09  94.05  1.812430e+11
689009.XSHG        5.087034e+07  44.22  2.249486e+09

[5189 rows x 3 columns]

In [73]:
#get_price("300750.XSHE",start_date="2026-04-21",end_date="2026-04-21")
get_shares("300750.XSHE", start_date="2026-04-21", end_date="2026-04-21",  expect_df=True, market='cn').droplevel(1)

,total,circulation_a,non_circulation_a,total_a,preferred_shares,free_circulation
order_book_id,,,,,,
300750.XSHE,4.564080e+09,4.256850e+09,151314830.0,4.408165e+09,0.0,2.404548e+09

In [ ]:
#check the weight change是不是在6、12月底
temp = index_weights("000300.XSHG",start_date="2025-06-15", end_date="2025-7-16")
df_wide = temp.unstack(level='order_book_id')['weight']
# 计算每天与前一天的权重变化
weight_changes = df_wide.diff()
# 计算每天所有股票权重变化的绝对值之和
daily_change_sum = weight_changes.abs().sum(axis=1)
# 找到变化最大的三天
top_3_days = daily_change_sum.nlargest(3)
print("变化最大的三天：")
print(top_3_days)

变化最大的三天：
date
2025-06-30    0.06589
2025-06-16    0.00000
2025-06-17    0.00000
dtype: float64

In [24]:
bardir = "E:/SJTU/实习/国泰海通/barra因子/data_base/barra_data/全A_M"
exp_file = f"{bardir}/米筐全A_20_26M_dict.pkl"
with open(exp_file, 'rb') as f:
    ex_dict = pickle.load(f)
ex_dict[pd.Timestamp('2020-01-23 00:00:00')]

,size,non_linear_size,momentum,liquidity,book_to_price,leverage,growth,earnings_yield,beta,residual_volatility,...,家用电器,基础化工,非银金融,社会服务,轻工制造,国防军工,美容护理,煤炭,食品饮料,钢铁
order_book_id,,,,,,,,,,,,,,,,,,,,,
000001.XSHE,1.117465,-0.446296,0.742415,-0.263541,0.519131,0.624373,-0.109217,0.931493,0.334312,-0.558799,...,0,0,0,0,0,0,0,0,0,0
000002.XSHE,1.117465,-0.446296,0.256587,0.187758,0.470296,2.243713,0.702882,2.229637,-0.060608,-0.297170,...,0,0,0,0,0,0,0,0,0,0
000004.XSHE,-2.206469,0.105020,0.098963,1.284773,-1.552433,-1.648610,0.857134,-1.316894,0.442339,0.525321,...,0,0,0,0,0,0,0,0,0,0
000005.XSHE,-2.383683,-0.283499,-0.749240,0.670899,-0.376115,-0.797164,2.283547,-0.562908,0.514077,-0.710268,...,0,0,0,0,0,0,0,0,0,0
000006.XSHE,-1.618753,0.852114,-0.888518,0.279241,0.734496,0.845181,0.120869,1.561285,0.238824,-0.991817,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
688368.XSHG,-1.578207,0.876959,0.324078,1.480488,-1.519184,-0.819167,0.021217,-1.753384,1.158141,0.653670,...,0,0,0,0,0,0,0,0,0,0
688369.XSHG,-1.942995,0.535521,-0.158730,1.749500,-1.453840,-0.752765,-0.407724,-1.635410,1.402897,0.408299,...,0,0,0,0,0,0,0,0,0,0
688388.XSHG,-0.946394,0.922703,-0.651801,1.343771,-1.191046,-1.733451,0.450008,-1.383932,0.176913,0.578538,...,0,0,0,0,0,0,0,0,0,0
688389.XSHG,-1.483258,0.923459,-0.556696,0.537953,-1.420968,-1.427301,0.467651,-1.686298,-0.417713,0.912260,...,0,0,0,0,0,0,0,0,0,0
688399.XSHG,-1.793465,0.708660,-0.550892,2.224719,-1.470504,-1.342964,0.352898,-1.652682,-0.418442,0.910979,...,0,0,0,0,0,0,0,0,0,0